### PR TITLE
Allow sections to be skipped in skosify.cfg

### PR DESCRIPTION
**Pull request by danmichaelo**
Makes all sections optional. Plus, use `configparser. read_file` on newer Python versions to avoid DeprecationWarning in python 3.6

### CODE REVIEW

**Comment by osma** [comment]
Travis build on Python 2.7 failed with this error:
`AttributeError: SafeConfigParser instance has no attribute 'read_dict'`

I think we still want to keep Python 2.7 compatibility, so can you work around this?

**Comment by danmichaelo** [comment]
A little messy, but here we go. The ConfigParser module annoys me every time I use it.

**Comment by osma** [comment]
Thanks, and sorry for the delay!
